FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["ProductCatalogUI.csproj", "./"]
RUN dotnet restore "./ProductCatalogUI.csproj"
COPY . .

RUN dotnet build "ProductCatalogUI.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "ProductCatalogUI.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ProductCatalogUI.dll"]
