apiVersion: v1
kind: Service
metadata:
    name: ui-node-port
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          nodePort: 31516
    selector:
        component: productcatalogui
