version: '3.4'

services:
  productcatalogapi:
    image: nandank81/productcatalogapi
    build:
      context: ProductCatalogApi
      dockerfile: DockerFile
    ports:
      - 5001:80
    environment:
      - ConnectionString__DefaultConnection=Server=db;database=ProductCatalog;User Id=sa;Password=Password@123
    depends_on: 
      - db
    networks: 
      - catalognetwork
  productcatalogui:
    image: nandank81/productcatalogui
    environment:
      - productcatalogapi=http://productcatalogapi
    build:
      context: ProductCatalogUI
      dockerfile: DockerFile
    ports:
      - 5002:80
    depends_on: 
      - productcatalogapi
    networks: 
      - catalognetwork
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    expose:
      - 1433
    networks: 
      - catalognetwork
    volumes:  
      - mssqlsystem:/var/opt/mssql3/
      - mssqluser:/var/opt/sqlserver
networks: 
  catalognetwork:
    driver: bridge
volumes: 
  mssqlsystem:
    external: false
  mssqluser:
    external: false
  