apiVersion: v1
kind: Pod
metadata:
  name: ToDoListAPI-Pod
  labels:
    component: ToDoListAPI-Pod
spec:
  containers:
  - name: ToDoList.API
    image: nandank81/todolist.api
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5001
