apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: todolistui-pod
  template:
    metadata:
      labels:
        component: todolistui-pod
    spec:
      containers:
      - name: todolistui
        image: nandank81/todolistui
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5003
