apiVersion: v1
kind: Service
metadata:
    name: api-node-port
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          nodePort: 31515
    selector:
        component: api
